version: '2.3'
services:
  jekyll:
    image: jekyll/jekyll:pages
    environment:
    - JEKYLL_ENV=production
    command: jekyll build --safe
    volumes:
    - './_config.yml:/srv/jekyll/_config.yml:ro'
    - './index.markdown:/srv/jekyll/index.markdown:ro'
    - './en.markdown:/srv/jekyll/en.markdown:ro'
    - './favicon.ico:/srv/jekyll/favicon.ico:ro'
    - './robots.txt:/srv/jekyll/robots.txt:ro'
    - './yarn.xml:/srv/jekyll/yarn.xml:ro'
    - './yarn-synsets.csv:/srv/jekyll/yarn-synsets.csv:ro'
    - './_site:/srv/jekyll/_site/'
